import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/local";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
    >
      <body className={`${roboto.className} min-h-full flex flex-col`}>{children}</body>
    </html>
  );
}
